[package]
name = "room"
version = "1.1.1"
edition = "2021"
authors = ["Lucas Rosa <x@rvcas.dev>"]
publish = false

[dependencies]
ansi_term = "0.12.1"
chrono = "0.4.26"
owo-colors = "3"
zellij-tile = "0.41"

